# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
      login_security_provider:
        entity:
          class: AppBundle:User
          property: email

      in_memory:
        memory: ~
          # users:
          #  rummykhan:
          #    password: rummykhan
          #    roles: ROLE_ADMIN

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            # Un-Comment below line to use Basic Http Authentication
            # http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            logout:
              csrf_parameter:       _token
              csrf_token_generator: security.csrf.token_manager
              csrf_token_id:        logout
              path:                 /logout
              target:               /login
              invalidate_session:   true

            form_login:
              provider:             login_security_provider
              check_path:           /login
              username_parameter:   email
              password_parameter:   password
              post_only:            true
              login_path:           /login
              target_path_parameter: nextPath
              failure_path_parameter: failPath
              csrf_token_generator: security.csrf.token_manager

    access_control:
        # Un-Comment Below line to use with Http Authentication
        - { path: ^/posts, roles: ROLE_USER }

    encoders:
      AppBundle\Entity\User:
        algorithm: sha512
        encode_as_base64: true
        iterations: 5000
      # Un-Comment Below line to use with Basic Http Authentication
      #Symfony\Component\Security\Core\User\User: plaintext